name: artic-ncov2019
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - nodejs=12
  - biopython=1.74
  - bwa=0.7.17=pl5.22.0_2
  - clint=0.5.1=py36_0
  - eigen=3.2=3
  - pysam=0.15.3
  - pyvcf=0.6.8=py36_0
  - ete3=3.1.1=py36_0
  - goalign=0.2.8=0
  - gotree=0.2.10=0
  - libdeflate=1.3
  - muscle=3.8.1551=2
  - nanopolish=0.13.0
  - medaka=0.12.1
  - longshot=0.4.1
  - phyml=3.3.20190909 # references etetoolkit build
  - pandas=0.23.0=py36_1
  - samtools=1.9
  - mafft=7.407=0
  - iqtree=1.6.12
  - datrie=0.8
  - snakemake-minimal=5.8.1
  - minimap2=2.17
  - seqtk=1.3
  - bcftools=1.9
  - artic-network::rampart=1.0
  - pip
  - pip:
    - git+https://github.com/artic-network/fieldbioinformatics.git
    - git+https://github.com/artic-network/Porechop.git@v0.3.2pre
    - binlorry==1.3.0_alpha1
    - ont-fast5-api
