name: Prepare Composite Reference Index
on: [workflow_dispatch]
jobs:
  prepare_composite_ref:
    name: Prepare Composite Reference Index
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: create artifacts dir to save test logs
      run: mkdir artifacts
    - name: install Conda
      run: bash .github/scripts/install_conda.sh
    - name: install bwa via Conda
      run: |
       export PATH=/opt/conda/bin:$PATH
       conda install -c bioconda bwa
    - name: Prepare composite reference sequence
      run: bash .github/scripts/prepare_composite_ref.sh 2> artifacts/prepare_composite_ref_artifact.log
    - uses: actions/upload-artifact@v2
      with:
        name: composite-reference-index
        path: $GITHUB_WORKSPACE/composite_ref/composite_human_viral_reference.fna.*
